package de.ItsAMysterious.mods.reallifemod;

import cpw.mods.fml.common.registry.GameRegistry;
import de.ItsAMysterious.mods.reallifemod.RealLifeMod;
import de.ItsAMysterious.mods.reallifemod.core.entities.cars.JeepData;
import de.ItsAMysterious.mods.reallifemod.core.items.AK47Item;
import de.ItsAMysterious.mods.reallifemod.core.items.CupType;
import de.ItsAMysterious.mods.reallifemod.core.items.EntityStoreItem;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemBaby;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemBattleAxe;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemBinoculars;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemChainsaw;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemCigarette;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemExternalDevice;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemIdentityCard;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemKatana;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemKnife;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemLawnMower;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemMP3Player;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemRPG;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemRawStick;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemSaw;
import de.ItsAMysterious.mods.reallifemod.core.items.ItemUzi;
import de.ItsAMysterious.mods.reallifemod.core.items.NPCPlacer;
import de.ItsAMysterious.mods.reallifemod.core.items.RobotPlacer;
import de.ItsAMysterious.mods.reallifemod.core.items.itemEmergencyHelicopter;
import de.ItsAMysterious.mods.reallifemod.core.items.itemcircuit;
import de.ItsAMysterious.mods.reallifemod.core.items.clothes.fireprotectionsuite;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemBanana;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemDough;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemFoodGeneric;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemNoodlesoup;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemSalt;
import de.ItsAMysterious.mods.reallifemod.core.items.food.ItemToast;
import de.ItsAMysterious.mods.reallifemod.core.items.food.bottleWater;
import de.ItsAMysterious.mods.reallifemod.core.items.food.emptyBottle;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemChips;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemCracker;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemCup;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemGingerbread;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemKetchup;
import de.ItsAMysterious.mods.reallifemod.core.items.food.itemSugarPole;
import de.ItsAMysterious.mods.reallifemod.core.items.industrial.ItemCoke;
import de.ItsAMysterious.mods.reallifemod.core.items.industrial.ItemScrabbedMetal;
import de.ItsAMysterious.mods.reallifemod.core.items.industrial.ItemSteelAxe;
import de.ItsAMysterious.mods.reallifemod.core.items.industrial.itemIngotSteel;
import de.ItsAMysterious.mods.reallifemod.core.items.meds.itemMed;
import de.ItsAMysterious.mods.reallifemod.core.items.meds.itemSyringe;
import de.ItsAMysterious.mods.reallifemod.core.items.outdoor.ItemRidingmower;
import de.ItsAMysterious.mods.reallifemod.core.items.roads.ItemLowry;
import de.ItsAMysterious.mods.reallifemod.core.items.roads.ItemTrafficlightConfigurator;
import de.ItsAMysterious.mods.reallifemod.core.items.roads.itemTrailer;
import de.ItsAMysterious.mods.reallifemod.core.items.tools.ItemAutoBuilder;
import de.ItsAMysterious.mods.reallifemod.core.toys.ItemRattle;
import de.ItsAMysterious.mods.reallifemod.items.VehicleItem;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor.ArmorMaterial;

public class RealLifeMod_Items {

   public static Item ID;
   public static Item customBlocksItem;
   public static Item ItemSnowMan;
   public static Item CustomSpade;
   public static Item cracker;
   public static Item salt;
   public static Item keksteig;
   public static Item banana;
   public static Item chips;
   public static Item ingotSteel;
   public static Item steelAxe;
   public static Item coke;
   public static Item Schrott;
   public static Item dirtySteel;
   public static Item emergencyHelicopter;
   public static Item Lowry;
   public static Item trailer;
   public static Item bottle;
   public static Item santa;
   public static Item itemGingerBread;
   public static Item ItemSugarPole;
   public static Item ak;
   public static Item guide;
   public static Item fireleggins;
   public static Item firehelmet;
   public static Item fireboots;
   public static Item fireplate;
   public static Item placer;
   public static Item toast;
   public static Item ketchup;
   public static Item uzi;
   public static Item jeep;
   public static Item emptybottle;
   public static Item circuitBrd;
   public static Item pillbox;
   public static Item syringe;
   public static Item cupEmpty;
   public static Item cupCappuccino;
   public static Item cupCoffee;
   public static Item cupHotChocolate;
   public static Item cupLatte;
   public static Item cupEspresso;
   public static Item cupTea;
   public static Item noodlesoup;
   public static Item saw;
   public static Item configurator;
   public static Item orange;
   public static Item robot;
   public static Item knife;
   public static Item mp3player;
   public static Item microSD;
   public static Item usbStick;
   public static Item catana;
   public static Item battleAxe;
   public static Item rawStick;
   public static Item RPG;
   public static Item chainsaw;
   public static Item binoculars;
   public static Item autobuilder;
   public static Item chair;
   public static Item lawnmower;
   public static Item ridingmower;
   public static Item rattle;
   public static Item baby;
   public static Item entitystoreitem;
   public static Item cigarette;
   public static List itemList = new ArrayList();


   public static void defineItems() {
      itemList.add(ingotSteel = (new itemIngotSteel()).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(cracker = (new itemCracker(2, 5.0F, true)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(salt = (new ItemSalt(-1, -1.0F, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(keksteig = (new ItemDough(2, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(steelAxe = (new ItemSteelAxe(RealLifeMod.Krupp)).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(ID = (new ItemIdentityCard()).func_77637_a(RealLifeMod.TLMEverydaylife));
      itemList.add(emergencyHelicopter = (new itemEmergencyHelicopter()).func_77637_a(RealLifeMod.medicine).setTextureName("reallifemod:WIP"));
      itemList.add(coke = (new ItemCoke()).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(Schrott = (new ItemScrabbedMetal()).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(banana = (new ItemBanana(5, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(chips = (new itemChips(5, 3.0F, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(Lowry = (new ItemLowry()).func_77637_a(RealLifeMod.Streets));
      itemList.add(trailer = (new itemTrailer()).func_77637_a(RealLifeMod.Streets).setTextureName("reallifemod:WIP"));
      itemList.add(bottle = new bottleWater());
      itemList.add(ItemSugarPole = (new itemSugarPole(1, 1.0F, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(itemGingerBread = (new itemGingerbread(1, 1.0F, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(ak = (new AK47Item()).func_77637_a(RealLifeMod.Work));
      itemList.add(firehelmet = (new fireprotectionsuite("fireprotection_helmet", ArmorMaterial.IRON, "fireprotectionsuite", 0)).func_77637_a(RealLifeMod.Work).setUnlocalizedName("fireprotection_helmet").setTextureName("reallifemod:WIP"));
      itemList.add(fireplate = (new fireprotectionsuite("fireprotection_chestplate", ArmorMaterial.IRON, "fireprotectionsuite", 1)).func_77637_a(RealLifeMod.Work).setUnlocalizedName("fireprotection_chestplate").setTextureName("reallifemod:WIP"));
      itemList.add(fireleggins = (new fireprotectionsuite("fire_leggins", ArmorMaterial.IRON, "fireprotectionsuite", 2)).func_77637_a(RealLifeMod.Work).setUnlocalizedName("fireprotection_leggins").setTextureName("reallifemod:WIP"));
      itemList.add(placer = (new NPCPlacer()).func_77637_a(RealLifeMod.Work));
      itemList.add(toast = (new ItemToast(1, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(ketchup = (new itemKetchup(1, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(uzi = (new ItemUzi()).func_77637_a(RealLifeMod.Work));
      itemList.add(emptybottle = (new emptyBottle()).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(circuitBrd = (new itemcircuit()).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(pillbox = (new itemMed(0, false)).func_77655_b("pillbox").setTextureName("reallifemod:medicine").setCreativeTab(RealLifeMod.medicine));
      itemList.add(syringe = (new itemSyringe()).func_77637_a(RealLifeMod.medicine));
      itemList.add(cupEmpty = new itemCup(0, false, CupType.CUP));
      itemList.add(cupCoffee = new itemCup(1, false, CupType.COFFEE));
      itemList.add(cupCappuccino = new itemCup(1, false, CupType.CAPPUCCINO));
      itemList.add(cupEspresso = new itemCup(1, false, CupType.ESPRESSO));
      itemList.add(cupLatte = new itemCup(1, false, CupType.LATTE));
      itemList.add(cupHotChocolate = new itemCup(1, false, CupType.HOTCHOC));
      itemList.add(cupTea = new itemCup(1, false, CupType.TEA));
      itemList.add(noodlesoup = (new ItemNoodlesoup(3, false)).func_77637_a(RealLifeMod.rlmfood));
      itemList.add(saw = (new ItemSaw()).func_77637_a(RealLifeMod.Work));
      itemList.add(configurator = new ItemTrafficlightConfigurator());
      itemList.add(orange = new ItemFoodGeneric(1, false, "orange", "orange"));
      itemList.add(new ItemFoodGeneric(1, false, "lemon", "lemon"));
      itemList.add(new ItemFoodGeneric(1, false, "kiwi", "Kiwi"));
      itemList.add(new ItemFoodGeneric(1, false, "coconut", "coconut"));
      itemList.add(new ItemFoodGeneric(1, false, "potatochips", "chips"));
      itemList.add(new ItemFoodGeneric(1, false, "salade", "salade"));
      itemList.add(new ItemFoodGeneric(1, false, "sunflowerseed", "sunflowerseeds"));
      itemList.add(robot = (new RobotPlacer()).func_77637_a(RealLifeMod.RLMTechnologie));
      itemList.add(knife = new ItemKnife());
      itemList.add(mp3player = new ItemMP3Player());
      itemList.add(microSD = new ItemExternalDevice());
      itemList.add(usbStick = (new ItemExternalDevice()).func_77655_b("USBStick").setTextureName("reallifemod:USBStick"));
      itemList.add(catana = new ItemKatana());
      itemList.add(battleAxe = new ItemBattleAxe());
      itemList.add(rawStick = new ItemRawStick());
      itemList.add(RPG = (new ItemRPG()).func_77637_a(RealLifeMod.Work));
      itemList.add(chainsaw = new ItemChainsaw());
      itemList.add(binoculars = new ItemBinoculars());
      itemList.add(autobuilder = new ItemAutoBuilder());
      itemList.add(lawnmower = new ItemLawnMower());
      itemList.add(ridingmower = new ItemRidingmower());
      itemList.add(rattle = (new ItemRattle()).func_77637_a(RealLifeMod.Toys));
      itemList.add(baby = (new ItemBaby()).func_77637_a(RealLifeMod.Toys));
      itemList.add(entitystoreitem = new EntityStoreItem());
      itemList.add(cigarette = (new ItemCigarette()).func_77637_a(RealLifeMod.Work));
      itemList.add(jeep = (new VehicleItem(new JeepData(), "cherockee")).func_77637_a(RealLifeMod.Streets));
      registerItems();
   }

   public static void registerItems() {
      for(int i = 0; i < itemList.size(); ++i) {
         GameRegistry.registerItem((Item)itemList.get(i), ((Item)itemList.get(i)).getUnlocalizedName());
      }

   }

   public static void registerItem(VehicleItem theItem) {
      itemList.add(theItem);
   }

}
